name: Check Mirrors

on:
  push:
    branches:
      - main

jobs:
  check-mirrors:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --version

      - name: Run mirror checker
        run: |
          chmod +x check_mirrors.sh
          ./check_mirrors.sh